### PR TITLE
amended typo on about section

### PR DESCRIPTION
**Pull request by Richardhartleydev**
## Amended typo in the about section that could be seen at smaller screen sizes <br> - see screenshot

Screenshot (2811)

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Hi @Richardhartleydev  Can you create a demo or elaborate a bit more !! It would be helpful for me !!

**Comment by Richardhartleydev** [comment]
index.html line 327 : <"button id="close-track-section">X</button">

As seen in the screenshot there is a typo "X" character at the far left of the page in the About Us section. This PR removed it.

This is the desktop version screenshot.

Screenshot (2812)

**Comment by c4coderandcreator** [comment]
I appreciate your accuracy !! I found the issue it is not on all devices but ya it is on some screens !! Though I request you to pull the main branch to your local and then push these changes !! There are certain PR's that got merged !! So just to tackle conflicts check it again

**Comment by Richardhartleydev** [comment]
Hope that works, thanks :)

**Pull request merged**
