### PR TITLE
Issue 1 redesign order now

### PR DESCRIPTION
**Pull request by beingsie**
## Brief Description

- This PR closes issue #1.
    - This pull request addresses various styling bugs and makes general styling updates:
        - Fixed the `l-header` positioning, changing it from `fixed` to `sticky` to resolve height issues affecting multiple divs.
        - Completely overhauled the design of `container-sam` for a more responsive and modern appearance.
        - **All media queries** have been removed, as the design now follows a mobile-first approach that translates well to desktop, tablet, and mobile views.
        - Resolved visual bugs in the `item-sam` section, where updating the quantity would cause the **sub** and **add** buttons to shift position based on the width of the quantity value.
        - Corrected the styling of `item-sam` buttons to ensure they display as circular shapes.
        - Fixed responsive issues with `food-content-sam` images, which had a width percentage exceeding 100% causing width breaks.
        - Updated the `head-content-sam` styling, including **border-radius** and **border-style**, to better match the improved UI.
        - Refined the styling of the search input to align with the new modern UI.
        - Enhanced the box-shadow for `main-head-sam` and `checkout-sam` for a more contemporary design.
        - Updated the `close-sam-section` button to better match the new UI.
        - Addressed visual issues caused by border styles for the **Checkout** and **Reset Cart** buttons, which were not initially displaying a border before the hover state.

## Desktop Screenshot preview:
image_2023-10-16_001137609

### CODE REVIEW

**Comment by beingsie** [comment]
Current conflicts are minimal, I believe footer links had their URL's inserted while I was working on this issue 😅

**Comment by c4coderandcreator** [comment]
That's amazing @beingsie !! I appreciate your Dedication and Quality of work !! I see some conflicts please resolve it

**Comment by beingsie** [comment]
We should be ok now 👍

**Comment by c4coderandcreator** [comment]
Thanks @beingsie for your valuable contribution !! Don't forget to star this repo for us 🫂 !!

**Pull request merged**
