### PR TITLE
Dark mode button fixed

### PR DESCRIPTION
**Pull request by akshad36**

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Finally !! @akshad36  !! Well Done !!

**Comment by c4coderandcreator** [comment]
Thank you @akshad36   !! For your valuable contribution !! Leave a Star to the Repo For Us !!

**Comment by akshad36** [comment]
Sorry for the  misbehaviour and misunderstanding by my side but i am at
beginner level  thank you so much for correcting me and hope you will add
it as hacktoberfest accepted

**Comment by c4coderandcreator** [comment]
I understand your feelings but don't be disheartened you did it well !! Look forward to contribute more and more , that's how you will grow, actually that's how we all will grow !! 


Thank you @akshad36  !! For your valuable contribution !! Leave a Star to the Repo For Us !!

**Comment by akshad36** [comment]
could u plz add a label of assign as my Pr is not relfecting in hacktoberfest

**Comment by c4coderandcreator** [comment]
wait for few minutes !! You will see a Timer of 7 days

**Pull request merged**
