### PR TITLE
Add tilt to about section images

### PR DESCRIPTION
**Pull request by buneeIsSlo**
Addresses #59 

- Apply tilt to all the images in the about section.

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
create the PR to UI-Improvement branch, you are currently making PR to main branch

**Comment by buneeIsSlo** [comment]
@c4coderandcreator I switched the branch. Kindly review the changes.

**Comment by buneeIsSlo** [comment]
Thanks for the opportunity!

**Comment by c4coderandcreator** [comment]
Thank you @buneeIsSlo   !! For your valuable contribution !! Leave a Star to the Repo For Us !!

**Pull request merged**
