### PR TITLE
UI changes

### PR DESCRIPTION
**Pull request by vedantheda**
Font changed to Montserrat,
adding some padding to Navbar,
changed Navbar color to Green,
added a line to separate footer

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Hey @vedantheda r u facing any issue ?

**Comment by vedantheda** [comment]
Yeah it was some issue with my GitHub Desktop I think

**Comment by c4coderandcreator** [comment]
Thank you @vedantheda !! If you like contributing , leave a star to the repo for us 🫂

**Comment by vedantheda** [comment]
Surely! Still looking to contribute more!

**Pull request merged**
