### PR TITLE
Minor UI change on the home page #19

### PR DESCRIPTION
**Pull request by uddiptojana10**
Fixes issue #19 

https://github.com/c4coderandcreator/Flavour-Fusion/assets/117717963/06dc8d95-1c3f-4bf1-b65d-ade94d4720d4

I have not done anything to the button that toggles between themes since there are people working on it.

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Good work @uddiptojana10  ! I appreciate your efforts 🫂 !! Please leave a star for us !!

**Comment by uddiptojana10** [comment]
@c4coderandcreator yes i noticed that as well. but i thought since that button is going to be fixed sooner or later with a custom button , I'd leave it be. But if you say I'll try and fix it

**Comment by c4coderandcreator** [comment]
Ya please @uddiptojana10,  we can't leave any bug for future if we have detected it 😄

**Comment by uddiptojana10** [comment]
ok i'll work on it. can i just change it to a custom button?

**Pull request merged**
