### PR TITLE
Order section modified with CSS

### PR DESCRIPTION
**Pull request by Shybymh**

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Hey @Shybymh  this branch has conflicts !! Resolve it !! Incase you face issue, let me know  !! Also describe the changes you made or share ss if possible !!

**Comment by Shybymh** [comment]
I have cleared all the conflicts. I have retained the code I have worked on which are  section element which has id= "sam" and div element with class = "checkout" . I moved the close button to a div element and added an h1 for "Your Cart". And their corresponding CSS.  All the animation CSS that was added after my fork is retained. 
[screencapture-127-0-0-1-5500-Flavour-Fusion-index-html-2023-10-16-14_08_45.pdf](https://github.com/c4coderandcreator/Flavour-Fusion/files/12922122/screencapture-127-0-0-1-5500-Flavour-Fusion-index-html-2023-10-16-14_08_45.pdf)

**Comment by c4coderandcreator** [comment]
Good Work @Shybymh  !! Leave a star to the repo for us 🫂

**Comment by c4coderandcreator** [comment]
Hey @Shybymh  Your section is breaking after the merge, kindly pull the main branch to your local machine and fix it !!

**Pull request merged**
