### PR TITLE
Fixed dark theme issue after reloading

### LINKED ISSUE #182: Fix: Dark mode theme issue after reloading
**Describe the bug**
When the website is in dark mode and we reload the website, the theme changes to light mode again.

**To Reproduce**
1. Change to dark mode using the sun button on navbar.
2. Refresh the website.

**Expected behavior**
The website should remain in the dark mode after reloading.

**Screenshots**

https://github.com/c4coderandcreator/Flavour-Fusion/assets/138107242/01388f01-d439-4372-ac51-4fc6ac826903

**Desktop (please complete the following information):**
 - OS: [all]
 - Browser[all]
 - Version [latest]

### PR DESCRIPTION
**Pull request by Srishdwi02**
**Description**
Fixed the issue by using session storage for storing the current theme.

**Issue**
Closes #182 

**Screenshots or GIFs (if applicable)**

https://github.com/c4coderandcreator/Flavour-Fusion/assets/138107242/dc713e2c-47fb-4e94-a90a-0ab92175bc45

**Checklist**
- [x] Code is well-documented
- [x] Code follows the project's code style
- [x] Tests have been added or updated

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Hey @Srishdwi02 I am away from my system (our festive season 💕) !! But i really want your efforts to get counted, so I am approving it but do me favour , once I approve it check for the applied changes !!

**Comment by Srishdwi02** [comment]
Thankyou for counting on me . I will surely check the applied changes on the website.

**Comment by c4coderandcreator** [comment]
> Thankyou for counting on me . I will surely check the applied changes on the website.

Thanks a Ton and Happy Navratri to you and your family ❤️🙏

**Comment by Srishdwi02** [comment]
Happy navratri to you and your family too!

**Pull request merged**
