### PR TITLE
ordered feature

### PR DESCRIPTION
**Pull request by VIDYA1980**
have added the feature where it gets updated such that when user clicks on the cafe it gets marked as ordered and others are unordered i just added as a feature im not sure if it meets requirements of the issue,kindly do let me know if this feature to be modified

image

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Hey @VIDYA1980  I like your efforts but the feature should be like :
- when when user type in the cafe section it should suggest the cafe as displayed the image but if you are assigning it as ordered then that cafe should be clickable and after the click whatever is ordered from the cafe will be displayed !! you try this feature by generating dummy list of orders !!

Feel free to drop questions or if you need any help !!

**Comment by c4coderandcreator** [comment]
Also your PR has conflicts !! resolve it

**Comment by VIDYA1980** [comment]
Ooh can you help me to solve this?

**Comment by c4coderandcreator** [comment]
you have to pull the code in your code editor then try resolving conflicts there !!

**Comment by VIDYA1980** [comment]
Ok, I will try.

**Pull request closed without merging**
