### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ranixhirani**
logo updated

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Please follow the contributing guidelines and let me know if you face any issue !! Also this PR is created with main branch , you should create the PR with UI-Improvement branch . And make sure you pull the repo before creating the PR (Just to avoid conflicts)

**Comment by ranixhirani** [comment]
I switched the branch but now I am facing this issue. Can you help me with
it?

**Comment by c4coderandcreator** [comment]
Ya @ranixhirani tell me what issue are you facing... If you cannot write it here try reaching me via email !! so that I can address it better or will schedule a meet to resolve this if needed !!

**Comment by ranixhirani** [comment]
While pushing my changes in the branch I am receiving message from GitBash
that I don't have the permission to do so. Kindly check the screenshot that
i am attaching with this email.

**Comment by c4coderandcreator** [comment]
Hey @ranixhirani  please share that email to : coderandcreator@gmail.com

**Pull request closed without merging**
