### PR TITLE
Preloader animation was added.

### PR DESCRIPTION
**Pull request by Light13008**
Preloader animation was added with Footers.

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
hey @Light13008  !! your code is messing with the dom part of the website , check that !! mostly with menu section and about section  !!

**Comment by Light13008** [comment]
can you send the screenshots of the problem ur facing, so that i can
correct them.

i will work on them asap, just send me the screenshots.

**Comment by c4coderandcreator** [comment]
there are lot , let me list them out :
- menu section irresponsive
- about section not visible 
- menu section is included in homepage , which should not be 

and  review it on your end too !! because these are just a name to few

**Comment by Light13008** [comment]
looking into it.

**Pull request merged**
