### PR TITLE
Improvements in Folder structure

### PR DESCRIPTION
**Pull request by Rock0007**
Issue Related to #257 

/Flavor-Fusion
├── css
│ └── styles.css
├── js
│ └── script.js
├── resources
│ ├── pages
└── index.html

@c4coderandcreator The index.html is functioning well with all pages including orders Page.

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
resolve the conflicts

**Comment by Rock0007** [comment]
> resolve the conflicts

i don't see any issues with this conflicts. index.html working good with all pages. Im unable to solve this.

**Comment by c4coderandcreator** [comment]
image

**Comment by Rock0007** [comment]
> image
> 
> 

You can Ignore the conflicts and merge it. Though it will perfectly.

**Comment by c4coderandcreator** [comment]
no bro cant risk it , just resolve so that i can merge , or I will do it in my free time

**Comment by Rock0007** [comment]
Assign me and give labels. This is my last PR out of 4. Let me finish successfully. Thank you.

**Comment by Rock0007** [comment]
> no bro cant risk it , just resolve so that i can merge , or I will do it in my free time

Create one more branch, I will change the base branch to that new branch. There you can merge it.

**Pull request closed without merging**
