### PR TITLE
[fix] Broken slide on review section

### PR DESCRIPTION
**Pull request by Petsamuel**
fixed the jQuery CDN, that prevented the slide from working. 

test link: https://shiny-dollop-55gj4r6g4qv34w7g-3000.app.github.dev/

### CODE REVIEW

**Comment by Petsamuel** [comment]
@c4coderandcreator I noticed the slider was broken so I fixed it, 
kindly review.

**Comment by c4coderandcreator** [comment]
Hey @Petsamuel  The demo is not accessible , kindly provide the demo with gif/video !!

**Comment by c4coderandcreator** [comment]
Also create the PR with UI-Improvement branch

**Comment by Petsamuel** [comment]
@c4coderandcreator is this issue resolved ? should go ahead with the changes you requested?

**Pull request closed without merging**
