### PR TITLE
Social links added, Closes #6

### LINKED ISSUE #6: Social media links not working

### PR DESCRIPTION
**Pull request by Shybymh**

### CODE REVIEW

**Comment by c4coderandcreator** [comment]
Hey @Shybymh  Please describe the changes you made in this PR !! and Thanks in advance for your contribution !!

**Comment by c4coderandcreator** [comment]
I have seen your changes and it looks good !! But from next time please elaborate your PR  !! And Ya Please Star this Repo ❤️

**Comment by Shybymh** [comment]
Since the site doesn't have social media now, I have added the facebook/twitter/instagram links ("https://www.facebook.com" , "https://www.twitter.com", "https://www.instagram.com") that will take user to the social media page instead of staying in the site's home page.

**Comment by c4coderandcreator** [comment]
@Shybymh Much better !! Though your PR is reviewed and Merged successfully !! Thanks for contributing to Flavour-Fusion !! Make sure you star the repo !!

**Pull request merged**
