### PR TITLE
fix: swiper slider component disortion ⚒️✨ 

### LINKED ISSUE #190: bug: swiper slider component disortion 🙅🏻❌
**Describe the bug**
- The bug is about the disortion of swiper sliders, border radius of each sliders are being causing disortion during sliding.

**To Reproduce**
1. Go to 'Menu' section of Flavor Fusion
2. See the error during sliding

**Expected behavior**
- Border radius needs to be applied to the Swiper component's wrapper instead of applying them on individual sliders

**Screenshots**
Capture_2023-10-22-19-13-03

**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 104.2

**Smartphone (please complete the following information):**
 - Device: Nokia 6.1
 - OS: Android 10
 - Browser: Chrome
 - Version: 113

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Screenshots

|||
|:---:|:---:|
|**BEFORE**|BEFORE|
|**AFTER**|AFTER|
||

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hi there @c4coderandcreator 👋🏻, Your review is appreciated!

**Comment by c4coderandcreator** [comment]
Thanks for contributing @0xabdulkhalid  !! it works fine for me !!

**Comment by 0xabdulkhalid** [comment]
Please add `hacktoberfest` labels, @c4coderandcreator.

**Comment by c4coderandcreator** [comment]
> Please add `hacktoberfest` labels, @c4coderandcreator.

It will fetch don't worry !!

**Pull request merged**
